<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>SSX_Library</RootNamespace>
    <AssemblyName>ssxlevel</AssemblyName>
    <NoWarn>CS0168;CS0219;CS0414;CS0649;CS8632;CS0108;CS0162;CS0169;CS1998;CS0618;CS8981;CS0105;CS0472;CS0252;CS0164;CS0109;CS0659;CS0661;CS8600;CS8601;CS8602;CS8603;CS8604;CS8618;CS8625;CS8765;CS8767;SYSLIB0011</NoWarn>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../lib/SSX-Library/**/*.cs" Exclude="../lib/SSX-Library/obj/**;../lib/SSX-Library/bin/**" />
    <Reference Include="../dll/BCnEncoder.dll" />
    <Reference Include="../dll/CommunityToolkit.HighPerformance.dll" />
    <Reference Include="../dll/ICSharpCode.SharpZipLib.dll" />
    <Reference Include="../dll/Newtonsoft.Json.dll" />
    <Reference Include="../dll/SharpGLTF.Core.dll" />
    <Reference Include="../dll/SharpGLTF.Runtime.dll" />
    <Reference Include="../dll/SharpGLTF.Toolkit.dll" />
    <Reference Include="../dll/SixLabors.Fonts.dll" />
    <Reference Include="../dll/SixLabors.ImageSharp.dll" />
    <Reference Include="../dll/SixLabors.ImageSharp.Drawing.dll" />
    <Reference Include="../dll/System.IO.Hashing.dll" />
  </ItemGroup>
</Project>
